<?php

//Baut die Form fürs Admininterface auf, wo die vorgeschlagenen Interessen bestätigt oder gelöscht werden können
function interests_suggestions_form($form, &$form_state) {

    //CSS hinzufügen
    drupal_add_css(drupal_get_path('module', 'alumni_interests_suggestions') . '/css/ais_custom.css', array('group' => CSS_DEFAULT));

    $form = array();

    //Fieldset defineiren
    $form['interests_suggestions'] = array(
        '#type' => 'fieldset',
        '#title' => t('Vorgeschlagene Interessen bearbeiten'),
        '#tree' => TRUE,
    );

    //Vorschläge aus der DB laden
    $query = db_select('alumni_interests_suggestions', 'ais');
    $query->fields('ais', array('id', 'name'));
    $result = $query->execute();

    if ($result->rowCount() == 0) {
        $form['interests_suggestions']['no_entries'] = array(
            '#markup' => '<span>' . t('Keine Vorschläge vorhanden.') . '</span>',
        );
    } else {
        $counter = 0;

        //Für jeden Vorschlag ein Textfeld mit dem Titel des Vorschlags und einem Selectfeld mit den Optionen definieren
        foreach ($result as $data) {
            $form['interests_suggestions'][$counter]['interest_name'] = array(
                '#type' => 'textfield',
                '#default_value' => $data->name,
                '#prefix' => '<div class="left-floated-element">',
                '#suffix' => '</div>',
            );

            $options = array(
                'publish' => t('Veröffentlichen'),
                'remove' => t('Löschen')
            );

            $form['interests_suggestions'][$counter]['interest_select'] = array(
                '#type' => 'select',
                '#options' => $options,
                '#empty_value' => SELECT_DEFAULT,
                '#prefix' => '<div class="left-floated-element">',
                '#suffix' => '</div><div class="clear-float"></div>',
            );

            //Die ID wird für die Funktion zum Speichern benötigt, daher wird ein verstecktes Feld mit der ID definiert
            $form['interests_suggestions'][$counter]['interest_id'] = array(
                '#type' => 'hidden',
                '#value' => $data->id,
            );

            $counter++;
        }

        $form['save_button'] = array(
            '#type' => 'submit',
            '#value' => t('Speichern'),
        );
    }

    return $form;
}

//Funktion wird aufgerufen, wenn im Admininterface der Buttom zum Speichern bei den vorgeschlagenen Interessen gedrückt wird
function interests_suggestions_form_submit($form, &$form_state) {

    //Überprüfen, ob im Admininterface bei den Einstellungen zu diesem Modul eine Taxonomie für Interessen ausgewählt wurde,
    //in die akzeptierte Vorschläge mit aufgenommen werden soll
    if (!empty(variable_get('aup_interests_taxonomy', ''))) {
        //Taxonomie laden, damit auch die vid geladen werden kann
        $vocab = taxonomy_vocabulary_machine_name_load(variable_get('aup_interests_taxonomy'));
        $vid = $vocab->vid;

        //Jedes Interessenfeld des Formulars iterieren
        foreach ($form_state['values']['interests_suggestions'] as $value) {

            //Wenn der Vorschlag veröffentlich werden soll, diesen der Taxonomie hinzufügen
            if ($value['interest_select'] != SELECT_DEFAULT) {
                if ($value['interest_select'] == 'publish') {
                    $term = new stdClass();
                    $term->name = $value['interest_name'];
                    $term->vid = $vid;
                    taxonomy_term_save($term);
                }

                //Wenn löschen oder veröffentlichen gewählt wurde, dann soll der Vorschlag aus der Tabelle für Vorschläge entfernt werden
                if ($value['interest_select'] == 'remove' || $value['interest_select'] == 'publish') {
                    db_delete('alumni_interests_suggestions')
                        ->condition('id', $value['interest_id'], '=')
                        ->execute();
                }
            }
        }
    }
}

//Funktion zum Festlegen der Links im Backend
function alumni_interests_suggestions_menu() {

    $items = array();

    //Datenbank Tabelle erstellen, falls nicht vorhanden
    $schema = alumni_interests_suggestions_dbschema();
    if(!db_table_exists('alumni_interests_suggestions')) {
        db_create_table('alumni_interests_suggestions', $schema['alumni_interests_suggestions']);
    }

    //Wenn im Admininterface eine Taxonomie ausgewählt wurde, in der die Vorschläge gespeichert werden sollen,
    //einen Link für die Übersichtsseite der Taxonomien erzeugen, mit dem zu den Vorschlägen gelangt werden kann
    if (!empty(variable_get('aup_interests_taxonomy', ''))) {
        $items['admin/structure/taxonomy/suggestions'] = array(
            'title' => t('Vorschläge'),
            'page callback' => 'drupal_get_form',
            'page arguments' => array('interests_suggestions_form'),
            'access arguments' => array('administer taxonomy'),
            'type' => MENU_LOCAL_TASK,
        );
    }

    //Link definieren, der die Vorschlagsseite repräsentiert
    $items['suggest/interest'] = array(
        'title' => t('Interesse vorschlagen'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('suggest_interest_form'),
        'access callback' => 'user_is_logged_in',
        'file' => 'suggest_interests.pages.inc',
    );
    return $items;

}

//Definieren des Arrays für die Datenbanktabellen und der Spalten
function alumni_interests_suggestions_dbschema()
{
    $schema = array();

    $schema['alumni_interests_suggestions'] = array(
        'description' => 'The table for interests suggestions',
        'fields' => array(
            'id' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0
            ),
            'name' => array(
                'type' => 'varchar',
                'length' => 255,
                'default' => ''
            ),
        )
    );

    return $schema;
}