<?php

/**
 * Implements hook_node_insert().
 */
function alumni_projects_node_insert($node)
{
    global $user;

    //Beim Hinzufügen eines Projekts, wenn es sich um den passenden Content Type handelt und der Benutzer kein Administrator ist, die Funktion setProjectManager
    //aufrufen, in der überprüft wird, ob es bereits einen Projektmanager gibt und ggf. den aktuellen Benutzer als Projektmanager setzt.
    if ($node->type === variable_get('aup_projects_content_type', '') && !user_has_role(3, user_load($user->uid))) {
        setProjectManager($node);
    }
}

/**
 * Implements hook_node_prepare().
 */
function alumni_projects_node_prepare($node)
{

    global $user;

    //Beim bearbeiten eines Projekts, wenn es sich um den passenden Content Type handelt und der Benutzer kein Administrator ist, die Funktion setProjectManager
    //aufrufen, in der überprüft wird, ob es bereits einen Projektmanager gibt und ggf. den aktuellen Benutzer als Projektmanager setzt.
    if (isset($node->nid) && $node->type === variable_get('aup_projects_content_type', '')
        && !user_has_role(3, user_load($user->uid))) {

        setProjectManager($node);

        //Überprüfen, ob der aktuelle Benutzer dem Projekt in der Datenbank zugeordnet ist und ggf. eine Fehlermeldung ausgeben
        $query = db_select('alumni_projects_access', 'apc');
        $query->fields('apc', array('user_id'));
        $query->condition('apc.node_id', $node->nid, '=');
        $query->condition('apc.user_id', $user->uid, '=');

        $result = $query->execute();


        if (!$result->fetchAssoc()) {
            drupal_set_message(t('Sie sind nicht dem Team des Projektes zugeordnet. Nur Teammitglieder können Ihr Projekt bearbeiten. ' .
                'Um Mitglied des Teams zu werden, muss dieses Projekt im Benutzerprofil im Bereich Jugend-Forscht Projekte hinzugefügt werden.'), 'error');
            drupal_access_denied();
            drupal_exit();

        } else {

            //Wenn der Benutzer dem Projekt bereits zugeordnet ist, überprüfen, ob der Projektmanager das Konto bereits freigeschaltet hat
            $query = db_select('alumni_projects_access', 'apc');
            $query->fields('apc', array('user_id'));
            $query->condition('apc.node_id', $node->nid, '=');
            $query->condition('apc.user_id', $user->uid, '=');
            $query->condition('apc.status', 0, '=');

            $result = $query->execute();

            if ($result->fetchAssoc()) {
                drupal_set_message(t('Der Projektmanager hat Ihr Konto für dieses Projekt noch nicht freigeschaltet.'), 'error');
                drupal_access_denied();
                drupal_exit();

            }
        }


    }

}

/**
 * Implements hook_node_view().
 */
function alumni_projects_node_view($node, $view_mode, $langcode)
{

    //Wenn es sich um den Content Type Projekte handelt, soll auf der Ansichtsseite der Projekte für den Projektmanager eine zusätzliche Box
    //angezeigt werden. In der Box wird ein Link zur Mitgliederverwaltung des Projekts angezeigt, die der Projektmanager aufrufen darf.
    if ($node->type === variable_get('aup_projects_content_type', '')) {

        global $user;
        $query = db_select('alumni_projects_access', 'apc');
        $query->fields('apc', array('user_id'));
        $query->condition('apc.node_id', $node->nid, '=');
        $query->condition('apc.user_id', $user->uid, '=');
        $query->condition('apc.manager', 1, '=');

        $result = $query->execute();

        if ($result->fetchAssoc()) {

            $managementLink = base_path() . 'projects/user-management/' . $node->nid;

            $markup =
                '<div class="projectmanager-box">
                <div>
                    Du bist Projektmanager!<br>
                    <a href="' . $managementLink . '">' . t('zur Mitgliederverwaltung') . '</a>
                </div>
            </div>';

            //Der Node die Box hinzufügen und die Gewichtung negativ setzen, damit die Box oberhalb des eigentlichen Inhalts des Projekts angezeigt wird
            $node->content['project_manager_info']['#weight'] = -1;
            $node->content['project_manager_info']['0']['#markup'] = $markup;
        }

    }

}


//Funktion, die überprüft, ob es einen Projektmanager bereits gibt und ggf. den aktuellen Benutzer als Projektmanager setzt
function setProjectManager($node) {
    $query = db_select('alumni_projects_access', 'apc');
    $query->fields('apc', array('user_id'));
    $query->condition('apc.node_id', $node->nid, '=');
    $query->condition('apc.manager', 1, '=');

    $result = $query->execute();

    if (!$result->fetchAssoc()) {

        global $user;

        $query = db_select('alumni_projects_access', 'apc');
        $query->fields('apc', array('user_id'));
        $query->condition('apc.node_id', $node->nid, '=');
        $query->condition('apc.user_id', $user->uid, '=');

        $result = $query->execute();

        //Wenn es keinen Projektmanager bereits für das Projekt gibt, der Benutzer aber dem Projekt bereits zugeordnet ist über seine im
        //Nutzerprofil angegebenen Projekte, wird der Eintrag in der Datenbank zu dem Benutzer geändert und dieser als Projektmanager gesetzt.
        if ($result->fetchAssoc()) {
            db_update('alumni_projects_access')
                ->fields(array(
                    'status' => 1,
                    'manager' => 1,
                ))
                ->condition('user_id', $user->uid, '=')
                ->condition('node_id', $node->nid, '=')
                ->execute();
        } else {
            //Wurde der Benutzer dem Projekt noch gar nicht zugeordnet, den direkt als Projektmanager dem Projekt hinzufügen
            db_insert('alumni_projects_access')
                ->fields(array(
                    'node_id' => $node->nid,
                    'user_id' => $user->uid,
                    'status' => 1,
                    'manager' => 1,
                ))
                ->execute();
        }
    }
}


//Funktion zum Erzeugen der intern Links für Drupal
function alumni_projects_menu() {

    $items = array();

    //Datenbanktabelle erzeugen, wenn diese noch nicht existiert.
    $schema = alumni_projects_dbschema();
    if(!db_table_exists('alumni_projects_access')) {
        db_create_table('alumni_projects_access', $schema['alumni_projects_access']);
    }

    $items['projects/user-management/%node'] = array(
        'title' => t('Projekt Mitgliederverwaltung'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('projects_user_management_form', 2),
        'access callback' => 'user_is_logged_in',
    );

    return $items;

}

//Funktion zum Erstellen des Formulars für die Mitgliederverwaltung bei Projekten
function projects_user_management_form($form, $form_state, $node) {

    global $user;

    //Überprüfen, ob der aktuelle Benutzer Projektmanager für das Projekt ist und die Seite aufrufen darf
    $query = db_select('alumni_projects_access', 'apc');
    $query->fields('apc', array('user_id'));
    $query->condition('apc.node_id', $node->nid, '=');
    $query->condition('apc.user_id', $user->uid, '=');
    $query->condition('apc.manager', 1, '=');

    $result = $query->execute();

    if (!$result->fetchAssoc()) {
        drupal_access_denied();
        drupal_exit();
    }

    //Zugeordnete Mitglieder zu dem Projekt laden
    $query = db_select('alumni_projects_access', 'apc');
    $query->fields('apc', array('user_id', 'status', 'manager'));
    $query->condition('apc.node_id', $node->nid, '=');

    $result = $query->execute();

    //Wenn es keine Projektmitglieder bisher gibt, entsprechenden Meldung festlegen
    if ($result->rowCount() == 1) {
        $form['no_result'] = array(
            '#markup' => '<span>' . t('Keine Mitglieder bisher in diesem Projekt') . '</span>',
        );
    } else {

        //Andernfalls eine Tabelle mit Projektmitgliedern generieren
        $form['users']['#tree'] = TRUE;


        $markup =
            '<table>
                <tr>
                    <th>' . t('Benutzer'). '</th>
                    <th>' . t('Status') . '</th>
                </tr>    
            ';

        $form['users']['table_start'] = array(
            '#markup' => $markup,
        );

        //optionsManager mit Projektmitgliedern für das Selectfeld zum Ändern des Projektmanagers
        $optionsManager = array();

        //Variable mit dem Projektmanager
        $projectmanager = '';

        $counter = 0;

        //Alle Projektmitglieder aus der Datenbank iterieren
        foreach ($result as $data) {

            //Benutzerobjekt laden
            $userLoad = user_load($data->user_id);

            //Wenn der Benutzer bereits für das Projekt freigeschaltet wurde, wird er dem options Array hinzugefügt.
            //Nur freigeschaltet Benutzer können als Projektmanager definiert werden
            if ($data->status == 1) {
                $optionsManager[$data->user_id] = $userLoad->name;
            }

            //Wenn der Benutzer Projektmanager ist, ihn in der Variable speichern. Wird für default_value des Selectfelds benötigt
            if ($data->manager == 1) {
                $projectmanager = $data->user_id;
            }

            //Wenn der Benutzer kein Manager ist, eine Zeile mit Daten zu dem Benutzer für die Tabelle erstellen
            if ($data->manager == 0) {
                $form['users'][$counter]['row_start'] = array(
                    '#markup' => '<tr>',
                );

                $form['users'][$counter]['user_name'] = array(
                    '#markup' => '<span>' . $userLoad->name . '</span>',
                    '#prefix' => '<td>',
                    '#suffix' => '</td>',
                );

                $options = array(
                    0 => t('kein Mitglied'),
                    1 => t('Mitglied'),
                );

                $form['users'][$counter]['user_status_select'] = array(
                    '#type' => 'select',
                    '#options' => $options,
                    '#default_value' => $data->status, //Je nachdem was in der Spalte status in der Datenbank steht, ist das Selectfeld mit "kein Mitglied" oder "Mitglied" vorbelegt
                    '#prefix' => '<td>',
                    '#suffix' => '</td>',
                );

                $form['users'][$counter]['user_id'] = array(
                    '#type' => 'hidden',
                    '#value' => $data->user_id,
                );

                $form['users'][$counter]['row_end'] = array(
                    '#markup' => '</tr>',
                );

                $counter++;
            }
        }

        $form['users']['table_end'] = array(
            '#markup' => '</table>',
        );

        //Node ID als hidden Feld hinzufügen. Wird beim Speichern der Form benötigt.
        $form['node_id'] = array(
            '#type' => 'hidden',
            '#value' => $node->nid,
        );

        //Selectfeld mit freigeschalteten Projektmitgliedern erzeugen, aktueller Projektmanager als default_value
        $form['projectmanager_select'] = array(
            '#title' => t('Projektmanager ändern'),
            '#type' => 'select',
            '#description' => t('Nur ein Benutzer kann Projektmanager sein. Wenn dieser geändert wird, hat der bisherige Projektmanager ' .
                'keinen Zugriff mehr auf die Mitgliederverwaltung dieses Projektes.'),
            '#options' => $optionsManager,
            '#default_value' => $projectmanager,
        );

        $form['save_button'] = array(
            '#type' => 'submit',
            '#value' => t('Speichern'),
        );

    }

    return $form;
}

//Funktion zum Speichern der Form
function projects_user_management_form_submit($form, &$form_state) {

    //Jedes Projektmitglied in der Tabelle iterieren und den status des Benutzers in der Datenbank atkualisieren
    foreach ($form_state['values']['users'] as $value) {
        db_update('alumni_projects_access')
            ->fields(array(
                'status' => $value['user_status_select'],
            ))
            ->condition('user_id', $value['user_id'], '=')
            ->condition('node_id', $form_state['values']['node_id'], '=')
            ->execute();
    }

    //Bei allen Projektmitgliedern Spalte manager auf 0 setzen
    db_update('alumni_projects_access')
        ->fields(array(
            'manager' => 0,
        ))
        ->condition('node_id', $form_state['values']['node_id'], '=')
        ->execute();

    //Aktuellen Benutzer aus dem Selectfeld für den Projektmanager als Manager des Projekts setzen
    db_update('alumni_projects_access')
        ->fields(array(
            'manager' => 1,
        ))
        ->condition('user_id', $form_state['values']['projectmanager_select'], '=')
        ->condition('node_id', $form_state['values']['node_id'], '=')
        ->execute();
}

//Definieren des Arrays für die Datenbanktabellen und der Spalten
function alumni_projects_dbschema() {
    $schema = array();

    $schema['alumni_projects_access'] = array(
        'description' => 'The table for access control on projects',
        'fields' => array(
            'node_id' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0
            ),
            'user_id' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0
            ),
            'status' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0
            ),
            'manager' => array(
                'type' => 'int',
                'not null' => TRUE,
                'default' => 0
            ),
        )
    );

    return $schema;
}