<?php

//Funktion durchsucht rekursiv das übergebene Array $value nach $key und ersetzt den HTML Code durch eigenen HTML Code
//Ändert den HTML Link beim PDF Export Button im Lebenslauf zum genauen Link zum Lebenslauf mit der ID vom Benutzer
//Bei dem Modul, dass den Button erzeugt, können keine dynamischen Links angegeben werden.
function array_markup_replace(&$value, $key, $string) {
    $result = false;

    if (!is_object($value)) {
        if (is_array($value)) {
            foreach ($value as $k => &$v) {
                if ($k === $key) {
                    $v[0]['#markup'] = $string;
                    break;
                }
                else {
                    array_markup_replace($v, $key, $string);
                }

            }
        }
    }
    return $result;
}

//Funktion durchsucht rekursiv das übergebene Array $value nach $key und blendet das gefunden Element aus.
//Blendet den PDF Export Button im Lebenslauf aus, wenn der HTML Code an die Exportfunktion übergeben wird
//oder der Benutzer nicht autorisiert ist diesen Button zu sehen
function array_search_hide(&$value, $key) {
    $result = false;

    if (!is_object($value)) {
        if (is_array($value)) {
            foreach ($value as $k => &$v) {
                if ($k === $key) {
                    hide($v);
                    break;
                }
                else {
                    array_search_hide($v, $key);
                }

            }
        }
    }
    return $result;
}

/**
 * Implements hook_user_view().
 */
function alumni_user_profile_user_view($account, $view_mode, $langcode)
{

    //Machine Name des PDF Export Buttons laden
    $PDFBtnMachineName = variable_get('aup_cv_export_pdf_machine_name', '');
    global $user;

    //Wenn der Benutzer sein eigenes Profil betrachtet oder der Benutzer ein Administrator ist, wird der korrekte HTML Link
    //zum Lebenslauf generiert und im content Array vom Account wird der Platzhalter Button für den Export durch den richtigen
    //Button ersetzt.
    if ($account->uid == $user->uid || user_has_role(3, user_load($user->uid))) {
        $markupHTML = '<a class="btn button export-pdf-btn" target="_blank" href="' . base_path() . 'usercv/' . $account->uid . '/pdf">' . t('PDF exportieren') . '</a><div class="clear-float"></div>';

        array_markup_replace($account->content, $PDFBtnMachineName, $markupHTML);
    } else {
        //Wenn der Benutzer den Button nicht sehen darf, dann wird dieser ausgeblendet
        array_search_hide($account->content, $PDFBtnMachineName);
    }
}


/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function alumni_user_profile_form_user_profile_form_alter(&$form, &$form_state, $form_id)
{

    //PDF Export Button in der Bearbeitungsform ausblenden. Wird dort nicht benötigt.
    $PDFBtnMachineName = variable_get('aup_cv_export_pdf_machine_name', '');

    array_search_hide($form, $PDFBtnMachineName);

}



//Funktion zum Erzeugen der intern Links für Drupal
function alumni_user_profile_menu() {

    $items = array();

    //Item für Ansicht des PDFs des Benutzerprofiles definieren
    $items['usercv/%user_uid/pdf'] = array(
        'title' => t('Lebenslauf exportieren'),
        'page callback' => 'print_usercv',
        'page arguments' => array(1),
        'access callback' => 'user_is_logged_in',
    );

    return $items;

}

//Funktion wird benötigt, damit der Platzhalter %user_uid aufgelöst werden kann
function user_uid_to_arg($arg) {
    // Give back the current user uid when called from eg. tracker, aka.
    // with an empty arg. Also use the current user uid when called from
    // the menu with a % for the current account link.
    return empty($arg) || $arg == '%' ? $GLOBALS['user']->uid : $arg;
}

//Dompdf wird verwendet, um aus dem HTML Code vom Lebenslauf ein PDF zu erzeugen
use Dompdf\Dompdf;
use Dompdf\Options;

function print_usercv($user_id) {


    //Überprüfen, ob der Benutzer existiert
    $userLoad = user_load($user_id);
    if (!$userLoad) {
        drupal_not_found();
        drupal_exit();
    }

    global $user;

    //Überprüfen, ob der Benutzer selber seine Seite aufruft oder ein Administrator dieses tut. Andere Benutzer sollen das PDF nicht exportieren dürfen
    if ($user_id != $user->uid && !user_has_role(3, user_load($user->uid))) {
        drupal_access_denied();
        drupal_exit();
    }

    //Autoloader von dompdf laden
    require_once 'sites/all/libraries/dompdf/autoload.inc.php';

    //Array der Ansicht des Benutzerprofils laden
    $userView = user_view($userLoad);

    $cvMachineName = variable_get('aup_cv_machine_name');

    //Lebenslauf anhand des Machinename aus dem Array extrahieren
    $userCV = $userView[$cvMachineName];

    //Machinename des PDF Export Buttons laden und den Button im Array ausblenden. Dieser soll im PDF nicht angezeigt werden
    $PDFBtnMachineName = variable_get('aup_cv_export_pdf_machine_name', '');
    array_search_hide($userCV, $PDFBtnMachineName);

    //Regular Font und Bold Font laden, falls diese im Backend definiert wurden. Werden zwei Fonts verwendet, da Überschriften im Lebenslauf
    //Bold sind und diese eine zusätzliche Font benötigen
    $fontPath = file_create_url('public://fonts') . '/';
    $regularFont = '';
    $boldFont = '';

    if (!empty(variable_get('aup_cv_regular_font_fid', '')))  {
        $file = file_load(variable_get('aup_cv_regular_font_fid', ''));

        if ($file) {
            $regularFont = $file->filename;
        }
    }

    if (!empty(variable_get('aup_cv_bold_font_fid', '')))  {
        $file = file_load(variable_get('aup_cv_bold_font_fid', ''));

        if ($file) {
            $boldFont = $file->filename;
        }
    }

    //Stylesheet laden, in HTML einbinden, zusätzlichen CSS Code für die Fonts und weiterer Formatierung definieren.
    $stylesheet = file_get_contents(drupal_get_path('theme', variable_get('aup_cv_theme_name', '')) . variable_get('aup_cv_theme_css_file', ''));

    $HTML = '<html>' .
        '<head>' .
        '<style>' .
        $stylesheet .

        '
        @font-face {
            font-family: "' . variable_get("aup_cv_font_family", "") . '";
            font-weight: normal;
            font-style: normal;
            src: url("' . $fontPath . $regularFont . '") format("truetype");
        }

        @font-face {
            font-family: "' . variable_get("aup_cv_font_family", "") . '";
            font-weight: bold;
            font-style: normal;
            src: url("' . $fontPath . $boldFont . '") format("truetype");
        }

        html {
            margin: 0;
        }

        body {
            margin: ' . variable_get("aup_cv_edge_margins", "1cm") . ';
            padding: 0;
            color: #000000;
            background: #fff;
            font-family: "' . variable_get("aup_cv_font_family", "") . '";
            
        }
        
        .cv-one-column .field-items {
            margin-left: 250px; 
        }
        
        .cv-user-image {
            width: ' . variable_get('aup_cv_image_size', '4cm') . ';            
            top: 0;
            right: 0;
        }
        
        .cv-user-image img {
            width: ' .variable_get('aup_cv_image_size', '4cm') . ';
            height: auto;
        }
        ' .

        '</style>' .
        '</head>' .
        '<body>' .
        //Array in HTML Code rendern
        drupal_render($userCV).
        '</body>' .
        '</html>';

    //Optionen definieren und dompdf übergeben
    $options = new Options();
    $options->set('isRemoteEnabled', true);

    //dompdf instanziieren
    $dompdf = new Dompdf($options);

    //HTML in dompdf laden
    $dompdf->loadHtml($HTML);
    $dompdf->setPaper('A4', 'portrait');

    //HTML als PDF rendern
    $dompdf->render();

    //Ergebnis an den Browser senden. Bei Attachment = 0 wird das PDF im Browser angezeigt, falls möglich
    $dompdf->stream('Lebenslauf.pdf', array('compress' => 1, 'Attachment' => 0));

    //Funktion aufrufen, damit es nicht zur Warnung Header already sent kommt
    drupal_exit();

}