<?php

//Funktion zum Erzeugen der intern Links für Drupal
function alumni_events_menu() {

    $items = array();


    $items['events/add'] = array(
        'title' => t('Veranstaltung hinzufügen'),
        'page callback' => 'add_event',
        //'page arguments' => array(1),
        'access callback' => 'user_is_logged_in',
        'file' => 'alumni_events.pages.inc',
    );


    return $items;

}
