<?php

/**
 * Implements hook_menu().
 */
function block_suggested_users_menu()
{
    $items = array();

    //Link wird aufgerufen, wenn weitere Seiten von vorgeschlagenen Benutzern geladen werden sollen
    $items['dashboard/get/suggested-users'] = array(
        'page callback' => 'get_next_suggested_users',
        'type' => MENU_CALLBACK,
        'access callback' => 'user_is_logged_in',
    );

    return $items;
}

/**
 * Implements hook_block_info().
 */
function block_suggested_users_block_info()
{
    //Block für vorgeschlagene Benutzer definieren
    $blocks['block_suggested_users'] = array(
        'info' => t('Benutzer mit gleichen Interessen'),
    );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function block_suggested_users_block_view($delta = '')
{
    $block = array();

    switch ($delta) {
        case 'block_suggested_users':
            //Genauere Informationen, wie Inhalt, CSS und JS Dateien definieren
            $block['subject'] = t('Benutzer mit gleichen Interessen');

            global $user;
            $path = drupal_get_path('module', 'block_suggested_users');

            $block['content'] = array(
                '#markup' => getSuggestedUsersList($user->uid),
                '#attached' => array(
                    'css' => array(
                        "$path/css/block_suggested_users.css",
                    ),
                    'js' => array(
                        "$path/js/block_suggested_users.js",
                    ),
                ),
            );


        break;
    }

    return $block;
}

//Funktion wird per AJAX aufgerufen, um weitere Seiten der vorgeschlagenen Benutzer zu laden
function get_next_suggested_users() {
    global $user;
    drupal_json_output(getSuggestedUsersList($user->uid));
    drupal_exit();
}

function getSuggestedUsersList($user_id) {

    $suggestedUsersListHtml = '';

    //Im Adminbereich definierte Systemnamen der Felder von Interessen im Benutzerprofil und in den Stellenangeboten auslesen
    //Diese werden zum joinen der Tabellen in der Datenbank benötigt, um die Einträge auszugeben, bei denen die Interessen übereinstimmen
    $userInterestsField = variable_get('aud_interests_user');

    //Pfad des Moduls holen, damit die CSS und JS Dateien richtig eingebunden werden können
    $path = drupal_get_path('module', 'block_suggested_users');

    //subQuery wird im eigentlichen Query dursucht. subQuery lädt alle Interessen des Benutzers. Im eigentlichen Query wird geguckt,
    //ob die Interessen der anderen Benutzer mit den Interessen des Benutzers übereinstimmen
    $subQuery = db_select('field_data_' . $userInterestsField, 'u2');
    $subQuery->fields('u2', array($userInterestsField . '_tid'));
    $subQuery->condition('u2.entity_id', $user_id, '=');

    //subQuery2 lädt alle Freunde des Benutzers. Im eigentlichen Query wird dann überprüft, dass die Benutzer nicht Freunde des
    //Benutzers sind, denn diese sollen nicht mehr Benutzer mit gleichen Interessen vorgeschlagen werden
    $subQuery2 = db_select('user_relationships', 'ur');
    $subQuery2->fields('ur', array('requestee_id'));
    $subQuery2->condition('ur.requester_id', $user_id, '=');

    $query = db_select('field_data_' . $userInterestsField, 'fd')->extend('PagerDefault');
    $query->distinct();
    //join mit users, um den Namen zu bekommen
    $query->join('users', 'us', 'fd.entity_id = us.uid');
    //join mit privacy_profile_fields_other settings, um herauszufinden, ob der Benutzer in seinem Profil angewählt hat, dass er
    //anderen Benutzern vorgeschlagen werden soll. leftJoin weil Benutzer standardmäßig angezeigt werden sollen, wenn diese bisher noch
    //keine Datenschutzeinstellungen gespeichert haben. In der Tabelle sind nämlich keine Einträge zu den Benutzern vorhanden, wenn diese
    //ihre Datenschutzeinstellungen noch überhaupt nicht gespeichert haben.
    $query->leftJoin('privacy_profile_fields_other_settings', 'ppf', 'fd.entity_id = ppf.user_id');
    $query->fields('fd', array('entity_id'));
    $query->fields('us', array('name'));
    $query->condition('fd.'. $userInterestsField . '_tid', $subQuery,'IN');
    $query->condition('fd.entity_id', $subQuery2,'NOT IN');
    $query->condition('fd.entity_id', $user_id,'!=');

    //Die Benutzer rausfiltern, die nicht anderen Bentuzern vorgeschlagen werden wollen
    $conGroup1 = db_and()
        ->condition('ppf.field_name', 'privacy_allow_suggestions', '=')
        ->condition('ppf.privacy', '0', '!=');

    //Die Benutzer, die noch gar nicht ihre Datenschutzeinstellungen gespeichert haben auslesen, da diese standardmäßig angezeigt werden sollen
    $conGroup2 = db_and()
        ->isNull('ppf.field_name')
        ->isNull('ppf.privacy');

    $query->condition(db_or()->condition($conGroup1)->condition($conGroup2));
    $query->orderBy('entity_id', 'DESC');
    $query->limit(5);

    $result = $query->execute();

    $paging = theme('pager');

    if ($result->rowCount() == 0) {
        $suggestedUsersListHtml .= '<p>' . t('Keine Benutzer mit gleichen Interessen gefunden.') . '</p>';
    } else {
        foreach ($result as $data) {
            $loadUser = user_load($data->entity_id);

            //Benutzerbild laden oder alternativ ein Platzhalter-Bild, wenn kein Bentuzerbild existiert
            $pictureLink = '';
            if (is_object($loadUser->picture)) {
                $pictureLink = file_create_url($loadUser->picture->uri);
            } else {
                $pictureLink = $path . '/images/no_pic.jpg';
            }

            $suggestedUsersListHtml .= '
                <div class="suggested-users-item">                                        
                    <div class="picture"><img src="' . $pictureLink . '" width="50px"></div>
                    <div class="name"><a href=" ' . base_path() . 'user/' . $data->entity_id . '" target="_blank">' . $data->name . '</a></div>
                </div>
            ';

        }

    }

    //Dem HTML Code noch die Navigation zu anderen Seiten hinzufügen
    $suggestedUsersListHtml .= $paging;
    return $suggestedUsersListHtml;
}