<?php


/**
 * Implements hook_field_info().
 */
function alumni_field_content_type_list_field_info()
{
    //Allgemeine Informationen zu diesem Feld
    return array(
        'alumni_content_type_list' => array(
            'label' => t('Content Type Liste'),
            'description' => t('Select Feld mit Auswahlliste eines Content Type'),
            'default_widget' => 'alumni_content_type_list_widget',
            'default_formatter' => 'alumni_content_type_list_formatter',
        ),
    );
}

/**
 * Implements hook_field_is_empty().
 */
function alumni_field_content_type_list_field_is_empty($item, $field)
{
    //Überprüft, ob etwas beim Speichern in dem Feld drin steht. Leere Felder sollen nicht in der Datenbank gespeichert werden
    return empty($item['alumni_content_type_list']);
}

/**
 * Implements hook_field_formatter_info().
 */
function alumni_field_content_type_list_field_formatter_info() {
    //Einen Formatter für die Anzeige festlegen
    return array(
        'alumni_content_type_list_formatter' => array(
            'label' => t('Standard'),
            'field types' => array('alumni_content_type_list'),
        ),
    );
}


/**
 * Implements hook_field_formatter_view().
 */
function alumni_field_content_type_list_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display)
{
    $element = array();

    //Erzeugen der Ausgabe für die Ansicht
    switch ($display['type']) {
        case 'alumni_content_type_list_formatter':
            foreach ($items as $delta => $item) {
                $element[$delta] = array(
                    '#markup' => $item['alumni_content_type_list'],
                );
            }
            break;
    }

    return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function alumni_field_content_type_list_field_widget_info() {

    //Widget für Bebarbeitungsform festlegen
    return array(
        'alumni_content_type_list_widget' => array(
            'label' => t('Auswahlliste'),
            'field types' => array('alumni_content_type_list'),
        ),
    );
}



/**
 * Implements hook_field_widget_form().
 */
function alumni_field_content_type_list_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element)
{
    //Formular für die Bearbeitungsform erstellen

    //Gespeicherte Eingabe des Selectfelds aus der Datenbank laden
    $value = isset($items[$delta]['alumni_content_type_list']) ? $items[$delta]['alumni_content_type_list'] : '';
    switch ($instance['widget']['type']) {
        case 'alumni_content_type_list_widget':

            $settings = $field['settings'];

            $options = array();

            //Alle Titel der Nodes des festgelegten Content Types laden und in options Array für das Selectfeld aufbereiten
            $query = db_select('node', 'n');
            $query->fields('n', array('title'));
            $query->condition('n.type', $settings['content_type_list_select'], '=');
            $query->condition('n.status', 1, '=');
            $query->orderBy('title', 'ASC');

            $result = $query->execute();

            foreach ($result as $data) {
                $options[check_plain($data -> title)] = check_plain($data -> title);
            }

            //Selectfeld zum Auswählen des Titels einer Node
            $element['alumni_content_type_list'] = array(
                '#type' => 'select',
                '#title' => $element['#title'],
                '#description' => $element['#description'],
                '#default_value' => $value,
                '#empty_option' => SELECT_DEFAULT,
                '#options' => $options,
                '#required' => $element['#required'],
                '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
                '#delta' => $delta,
            );
            break;
    }
    return $element;
}

/**
 * Implements hook_field_settings_form().
 */
function alumni_field_content_type_list_field_settings_form($field, $instance, $has_data)
{

    //Formular für die settings_form für die Konfiguration des Felds erstellen
    $form = array();

    $options = array();

    //Vorhandene Content Types laden und Namen des Content Types im options Array für das Selectfeld speichern
    $types = node_type_get_types();

    foreach ($types as $type) {
        $options[$type->type] = $type->type;
    }

    $settings = $field['settings'];

    //Selectfeld für die Auswahl eines Content Types definieren
    $form['content_type_list_select'] = array(
        '#type' => 'select',
        '#title' => t('Systemname des Content Types'),
        '#options' => $options,
        '#default_value' => isset($settings['content_type_list_select']) ? $settings['content_type_list_select'] : '',
        '#empty_option' => SELECT_DEFAULT,
        '#required' => TRUE,
    );

    return $form;
}